// build-corpus.mjs
// Pre-build/pre-dev hook: concatenates the assistant knowledge corpus
// (content/assistant-wiki/*.md) into a single TypeScript module that the
// /api/chat route imports.
//
// This is the "wiki LLM" grounding approach — the entire corpus (~20K
// tokens) is passed in the system prompt every query. No embeddings, no
// vector DB, no retrieval. The corpus is small enough that this is both
// simpler and (with Anthropic prompt caching) cheap.
//
// Output: lib/corpus.generated.ts
//   - ASSISTANT_CORPUS  : one big string, files joined with separators
//   - CORPUS_FILE_LIST  : array of filenames, used for citation validation
//
// Safe to run multiple times; idempotent. The output file is regenerated
// from scratch each run.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const portfolioRoot = resolve(__dirname, '..');
const corpusDir = join(portfolioRoot, 'content', 'assistant-wiki');
const outFile = join(portfolioRoot, 'lib', 'corpus.generated.ts');

// Read + sort by filename so the corpus order (and the prompt-cache key)
// is stable across runs.
const files = readdirSync(corpusDir)
  .filter((f) => f.endsWith('.md'))
  .sort();

if (files.length === 0) {
  console.error('[build-corpus] ERROR: no .md files found in content/assistant-wiki/');
  process.exit(1);
}

// Concatenate: a header line per file, then the file body, joined with a
// horizontal-rule separator so the model can tell file boundaries apart.
const corpus = files
  .map((f) => {
    const body = readFileSync(join(corpusDir, f), 'utf8').trim();
    return `### FILE: ${f}\n\n${body}`;
  })
  .join('\n\n---\n\n');

// Emit a TypeScript module. The corpus goes in a template literal; any
// backtick or ${ in the source content is escaped so the literal stays
// valid.
const escaped = corpus.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const fileList = JSON.stringify(files);

const out = `// AUTO-GENERATED by scripts/build-corpus.mjs — DO NOT EDIT.
// Regenerated on every \`npm run build\` and \`npm run dev\` (prebuild/predev).
// Source: content/assistant-wiki/*.md (${files.length} files).

/** The full assistant knowledge corpus, concatenated. Passed verbatim in
 *  the /api/chat system prompt (the "wiki LLM" grounding approach). */
export const ASSISTANT_CORPUS = \`${escaped}\`;

/** Filenames present in the corpus, in sorted order. Used to validate that
 *  model-emitted [^citations] reference files that actually exist. */
export const CORPUS_FILE_LIST: string[] = ${fileList};
`;

writeFileSync(outFile, out, 'utf8');

const kb = (Buffer.byteLength(corpus, 'utf8') / 1024).toFixed(1);
const approxTokens = Math.round(corpus.length / 4);
console.log(
  `[build-corpus] OK — ${files.length} files → lib/corpus.generated.ts ` +
    `(${kb} KB, ~${approxTokens} tokens)`
);
